<?php

return [
    'provider' => env('AI_PROVIDER', 'openrouter'),
    'base_url' => rtrim((string) env('AI_BASE_URL', 'https://openrouter.ai/api/v1'), '/'),
    'api_key' => env('AI_API_KEY'),
    'model' => env('AI_MODEL', 'openai/gpt-4.1-mini'),
    'timeout' => max(300, (int) env('AI_TIMEOUT', 300)),
    'connect_timeout' => max(5, (int) env('AI_CONNECT_TIMEOUT', 20)),
    'temperature' => (float) env('AI_TEMPERATURE', 0.1),
    'max_completion_tokens' => (int) env('AI_MAX_COMPLETION_TOKENS', 4096),
    'openrouter' => [
        'retry_attempts' => max(4, (int) env('AI_OPENROUTER_RETRY_ATTEMPTS', 4)),
        'retry_delay_ms' => max(500, (int) env('AI_OPENROUTER_RETRY_DELAY_MS', 1500)),
        'json_mode' => filter_var(env('AI_OPENROUTER_JSON_MODE', true), FILTER_VALIDATE_BOOL),
        'retry_without_json_mode' => filter_var(env('AI_OPENROUTER_RETRY_WITHOUT_JSON_MODE', true), FILTER_VALIDATE_BOOL),
        'reasoning_effort' => env('AI_OPENROUTER_REASONING_EFFORT', 'none'),
        'exclude_reasoning' => filter_var(env('AI_OPENROUTER_EXCLUDE_REASONING', true), FILTER_VALIDATE_BOOL),
    ],
    'dispatch_mode' => env('AI_DISPATCH_MODE', 'after_response'),
    'queue_connection' => env('AI_QUEUE_CONNECTION', ''),
    'queue' => env('AI_QUEUE', ''),
    'job_tries' => max(3, (int) env('AI_JOB_TRIES', 3)),
    'job_timeout' => max(600, (int) env('AI_JOB_TIMEOUT', 1800)),
    'job_backoff' => env('AI_JOB_BACKOFF', '30,90,180'),
    'execution' => [
        'enabled' => filter_var(env('AI_EXECUTION_ENABLED', true), FILTER_VALIDATE_BOOL),
        'timeout' => (int) env('AI_EXECUTION_TIMEOUT', 15),
        'php_binary' => env('AI_PHP_BINARY', ''),
    ],
    'max_extracted_chars' => (int) env('AI_MAX_EXTRACTED_CHARS', 60000),
    'max_excerpt_chars' => (int) env('AI_MAX_EXCERPT_CHARS', 8000),
    'max_files_per_review' => (int) env('AI_MAX_FILES_PER_REVIEW', 50),
    'max_csv_preview_rows' => (int) env('AI_MAX_CSV_PREVIEW_ROWS', 20),
    'max_sheet_preview_rows' => (int) env('AI_MAX_SHEET_PREVIEW_ROWS', 20),
    'max_sheet_preview_columns' => (int) env('AI_MAX_SHEET_PREVIEW_COLUMNS', 12),
    'zip' => [
        'max_entries' => (int) env('AI_ZIP_MAX_ENTRIES', 200),
        'max_depth' => (int) env('AI_ZIP_MAX_DEPTH', 5),
        'max_total_uncompressed_bytes' => (int) env('AI_ZIP_MAX_TOTAL_UNCOMPRESSED_BYTES', 52428800),
    ],
    'text_extensions' => [
        'txt', 'md', 'json', 'xml', 'yml', 'yaml', 'ini', 'env', 'csv', 'tsv',
        'php', 'js', 'ts', 'jsx', 'tsx', 'vue', 'py', 'java', 'kt', 'kts',
        'cs', 'go', 'rs', 'rb', 'c', 'cpp', 'cc', 'cxx', 'h', 'hpp', 'hh', 'hxx',
        'swift', 'sql', 'sh', 'ps1', 'html', 'htm', 'css', 'scss', 'less', 'blade.php',
    ],
    'code_extensions' => [
        'php', 'js', 'ts', 'jsx', 'tsx', 'vue', 'py', 'java', 'kt', 'kts',
        'cs', 'go', 'rs', 'rb', 'c', 'cpp', 'cc', 'cxx', 'h', 'hpp', 'hh', 'hxx',
        'swift', 'sql', 'sh', 'ps1', 'html', 'htm', 'css', 'scss', 'less',
    ],
    'supported_extensions' => [
        'txt', 'md', 'json', 'xml', 'yml', 'yaml', 'ini', 'env',
        'php', 'js', 'ts', 'jsx', 'tsx', 'vue', 'py', 'java', 'kt', 'kts',
        'cs', 'go', 'rs', 'rb', 'c', 'cpp', 'cc', 'cxx', 'h', 'hpp', 'hh', 'hxx',
        'swift', 'sql', 'sh', 'ps1', 'html', 'htm', 'css', 'scss', 'less',
        'docx', 'doc', 'xlsx', 'xls', 'csv', 'tsv', 'zip', 'rar', '7z',
    ],
];
